/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_controlador.vendedor;

import vista_controlador.crear_cuenta;
import vista_controlador.crear_cuenta;
import vista_controlador.vista_login;
import vista_controlador.vista_login;

/**
 *
 * @author WILLIAM
 */
public class vendedor_1 extends javax.swing.JFrame {

    /**
     * Creates new form vendedor_1
     */
    public vendedor_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        b_gen_venta = new javax.swing.JButton();
        b_search = new javax.swing.JButton();
        b_listar_prods = new javax.swing.JButton();
        b_listar_ventas = new javax.swing.JButton();
        b_cambiar_estado = new javax.swing.JButton();
        b_exit = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO VENDEDOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 590, -1));

        b_gen_venta.setBackground(new java.awt.Color(255, 255, 255));
        b_gen_venta.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_gen_venta.setForeground(new java.awt.Color(0, 0, 0));
        b_gen_venta.setText("generar venta");
        b_gen_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gen_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(b_gen_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 290, -1));

        b_search.setBackground(new java.awt.Color(255, 255, 255));
        b_search.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_search.setForeground(new java.awt.Color(0, 0, 0));
        b_search.setText("buscar producto");
        getContentPane().add(b_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 290, -1));

        b_listar_prods.setBackground(new java.awt.Color(255, 255, 255));
        b_listar_prods.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_listar_prods.setForeground(new java.awt.Color(0, 0, 0));
        b_listar_prods.setText("listar productos");
        getContentPane().add(b_listar_prods, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 290, -1));

        b_listar_ventas.setBackground(new java.awt.Color(255, 255, 255));
        b_listar_ventas.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_listar_ventas.setForeground(new java.awt.Color(0, 0, 0));
        b_listar_ventas.setText("listar ventas");
        getContentPane().add(b_listar_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 290, -1));

        b_cambiar_estado.setBackground(new java.awt.Color(255, 255, 255));
        b_cambiar_estado.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_cambiar_estado.setForeground(new java.awt.Color(0, 0, 0));
        b_cambiar_estado.setText("cambiar estado de venta");
        getContentPane().add(b_cambiar_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 290, -1));

        b_exit.setBackground(new java.awt.Color(255, 255, 255));
        b_exit.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_exit.setForeground(new java.awt.Color(0, 0, 0));
        b_exit.setText("SALIR");
        b_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_exitActionPerformed(evt);
            }
        });
        getContentPane().add(b_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 180, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/img1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_gen_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gen_ventaActionPerformed
        // TODO add your handling code here:
        crear_cuenta c1= new crear_cuenta();
        c1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_gen_ventaActionPerformed

    private void b_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_exitActionPerformed
        // TODO add your handling code here:
        vista_login v1 = new vista_login();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendedor_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendedor_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cambiar_estado;
    private javax.swing.JButton b_exit;
    private javax.swing.JButton b_gen_venta;
    private javax.swing.JButton b_listar_prods;
    private javax.swing.JButton b_listar_ventas;
    private javax.swing.JButton b_search;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
