/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_controlador.productos;
import Clases.Array_productos;
import Clases.Productos;
import javax.swing.JOptionPane;
import vista_controlador.admin.productos_1;
import proyecto_final.*;

/**
 *
 * @author WILLIAM
 */
public class nuevo_producto extends javax.swing.JFrame {
    Array_productos array_pro=new Array_productos();
    
    /**
     * Creates new form nuevo_producto
     */
    public nuevo_producto() {
        initComponents();
        array_pro.inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        precio_ = new javax.swing.JTextField();
        tipo_ = new javax.swing.JTextField();
        marca_ = new javax.swing.JTextField();
        nombre_ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MARCA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIPO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 480, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 220, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("CREAR PRODUCTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 220, -1));

        precio_.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        precio_.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        precio_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_ActionPerformed(evt);
            }
        });
        precio_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precio_KeyPressed(evt);
            }
        });
        getContentPane().add(precio_, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 140, -1));

        tipo_.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tipo_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipo_KeyPressed(evt);
            }
        });
        getContentPane().add(tipo_, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, -1));

        marca_.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        marca_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marca_KeyPressed(evt);
            }
        });
        getContentPane().add(marca_, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 140, -1));

        nombre_.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombre_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre_KeyPressed(evt);
            }
        });
        getContentPane().add(nombre_, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/img1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        productos_1 p1= new productos_1();
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void precio_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio_KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            precio_.setEditable(false);
        } else {
            precio_.setEditable(true);
        }
    }//GEN-LAST:event_precio_KeyPressed

    private void precio_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int codigo=array_pro.Correlativo();
        String nombre=nombre_.getText();
        String marca=marca_.getText();
        String tipo=tipo_.getText();
        float precio=Float.parseFloat(precio_.getText());
        if(nombre!="" && marca!="" && tipo!=""){
            Productos pro1=new Productos();
            pro1.setCodigo_producto(codigo);
            pro1.setMarca_producto(marca);
            pro1.setNombre_producto(nombre);
            pro1.setPrecio_producto(precio);
            pro1.setTipo_producto(tipo);

            array_pro.agregar(pro1);
            array_pro.grabar_archivo(pro1);
            
            JOptionPane.showMessageDialog(rootPane, "Registro completado");
            productos_1 p1= new productos_1();
            p1.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ningun casillero debe estar vacio");
            nombre_.setText("");
            marca_.setText("");
            tipo_.setText("");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tipo_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipo_KeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            tipo_.setEditable(false);
        } else {
            tipo_.setEditable(true);
        }
    }//GEN-LAST:event_tipo_KeyPressed

    private void marca_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marca_KeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            tipo_.setEditable(false);
        } else {
            tipo_.setEditable(true);
        }
    }//GEN-LAST:event_marca_KeyPressed

    private void nombre_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_KeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            tipo_.setEditable(false);
        } else {
            tipo_.setEditable(true);
        }
    }//GEN-LAST:event_nombre_KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField marca_;
    private javax.swing.JTextField nombre_;
    private javax.swing.JTextField precio_;
    private javax.swing.JTextField tipo_;
    // End of variables declaration//GEN-END:variables
}
