/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_controlador.proveedor;

import auxiliares.Auxiliares;
import javax.swing.JOptionPane;
import proyecto_final.Proveedor;
import proyecto_final.Proveedor_Array;

/**
 *
 * @author WILLIAM
 */
public class proveedor_buscar extends javax.swing.JFrame {
Proveedor_Array proveedor_a= new Proveedor_Array();
Auxiliares aux= new Auxiliares();
    /**
     * Creates new form proveedor_buscar
     */
    public proveedor_buscar() {
        initComponents();
        proveedor_a.inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ruc_ = new javax.swing.JTextField();
        b_buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ruc__ = new javax.swing.JLabel();
        razon_ = new javax.swing.JLabel();
        direccion_ = new javax.swing.JLabel();
        contacto1_ = new javax.swing.JLabel();
        contacto2_ = new javax.swing.JLabel();
        sucursal_ = new javax.swing.JLabel();
        website_ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("buscar proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 600, -1));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ruc:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        ruc_.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ruc_.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ruc_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ruc_KeyPressed(evt);
            }
        });
        getContentPane().add(ruc_, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, -1));

        b_buscar.setBackground(new java.awt.Color(255, 255, 255));
        b_buscar.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        b_buscar.setForeground(new java.awt.Color(0, 0, 0));
        b_buscar.setText("BUSCAR");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(b_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("website:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("dirección:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("contacto 2:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("contacto 1:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" sucursal:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("razon social:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ruc:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 160, -1));

        ruc__.setBackground(new java.awt.Color(255, 255, 255));
        ruc__.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        ruc__.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ruc__, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        razon_.setBackground(new java.awt.Color(255, 255, 255));
        razon_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        razon_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(razon_, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        direccion_.setBackground(new java.awt.Color(255, 255, 255));
        direccion_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        direccion_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(direccion_, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        contacto1_.setBackground(new java.awt.Color(255, 255, 255));
        contacto1_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        contacto1_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(contacto1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        contacto2_.setBackground(new java.awt.Color(255, 255, 255));
        contacto2_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        contacto2_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(contacto2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        sucursal_.setBackground(new java.awt.Color(255, 255, 255));
        sucursal_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        sucursal_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sucursal_, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        website_.setBackground(new java.awt.Color(255, 255, 255));
        website_.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        website_.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(website_, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/img1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruc_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ruc_KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            ruc_.setEditable(false);
        } else {
            ruc_.setEditable(true);
        }
    }//GEN-LAST:event_ruc_KeyPressed

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed
        String ruc = ruc_.getText();

        Proveedor p1 = proveedor_a.busqueda_proveedor(ruc);
        if (p1.getRuc()!="0") {
            ruc__.setText(p1.getRuc());
            razon_.setText(p1.getRaz_social());
            direccion_.setText(p1.getDireccion());
            contacto1_.setText(p1.getNom_contact1());
            contacto2_.setText(p1.getNom_contact2());
            website_.setText(p1.getWebsite());
            sucursal_.setText(p1.getSurcursal());

            ruc_.setText("");

        } else {
            ruc__.setText("");
            razon_.setText("");
            direccion_.setText("");
            contacto1_.setText("");
            contacto2_.setText("");
            website_.setText("");
            sucursal_.setText("");
            ruc_.setText("");
            JOptionPane.showMessageDialog(null, "No existe un proveedor con el RUC ingresado", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_b_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        proveedor p1 = new proveedor();
        aux.change_jf(p1, this);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedor_buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_buscar;
    private javax.swing.JLabel contacto1_;
    private javax.swing.JLabel contacto2_;
    private javax.swing.JLabel direccion_;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel razon_;
    private javax.swing.JTextField ruc_;
    private javax.swing.JLabel ruc__;
    private javax.swing.JLabel sucursal_;
    private javax.swing.JLabel website_;
    // End of variables declaration//GEN-END:variables
}
